require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

# Disable some failing rspec cops that fail from upgrading gems until we can clean things up a bit.
Naming/FileName:
  Exclude:
    - lib/amplitude-api.rb
RSpec/ExampleLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
